export enum ExerciseEventType {
  EXER_LIST_VIEW,
  EXER_LIST_VIEW_DELETE,
  EXER_GROUP_VIEW,
  EXER_GROUP_VIEW_DELETE,
  EXER_GROUP_EXERCISE_VIEW,
  EXER_GROUP_EXERCISE_DELETE = 5,
  EXER_EDIT,
  EXER_EDIT_INSTRUCTION,
  EXER_GROUP_INSTRUCTION,
  EXER_ADD,
  EXER_INSTRUCTION_DELETE,
}
export class ExerciseEvent {
  constructor() {}
}
